language: node_js
node_js: node
install: npm install
cache:
  directories:
    - "node_modules"
    - "downloads"
before_script:
  npm run update
script: npm test
after_success: npm run coverage
after_deploy: "Done"
