language: node_js
node_js: node
install: npm install
cache:
  directories:
    "node_modules"
before_script:
  npm install -g mocha@3.5.0
script: npm test
after_success: npm run coverage
after_deploy: "Done"
