#!/usr/bin/env node
'use strict';

const PORT = 3030;
const express = require('express');
const cors = require('cors');
const CardApi = require('./src/card-api');
const ErrorHandlers = require('./src/error-handlers');

const app = express();

app.use(cors());

// Expose the public directory as a static file resource
app.use(`/static`, express.static('static'));

// ?card=Plains
app.get('/card', CardApi.getCardJson);
app.get('/card/json', CardApi.getCardJson);

// ?card=Plains
app.get('/card/html', CardApi.getCardHtml);

// ?card=Plains
app.get('/image', CardApi.getCardImage);
app.get('/card/image', CardApi.getCardImage);

// Error handling
app.use(ErrorHandlers.logErrors);
app.use(ErrorHandlers.clientErrorHandler);
app.use(ErrorHandlers.errorHandler);

app.listen(PORT, () =>
    console.log(`MTG Card Finder listening on port ${PORT}`)
);

// Last resort
process.on('uncaughtException', (err) => {
  console.error(err);
});
