#!/usr/bin/env node
'use strict';

const express = require('express');
const _ = require('lodash');
const request = require('request');

const allSets = require('./data/AllSets.json');

const cardListFull = _.flatMap(allSets, (set) => set.cards);
const cardList = _.map(cardListFull, (card) => ({
    name: card.name,
    multiverseid: card.multiverseid,
    imageUrl: `http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=${card.multiverseid}`,
}));

let normalizeName = (name) => {
    return name.split(`//`)[0].toLowerCase().trim();
};

let cardMap = {};
cardList.forEach(card => {
    cardMap[normalizeName(card.name)] = card;
});

console.log(`Cards loaded: ${cardList.length}`);

const app = express();

app.get('/cards', function (req, res) {
  res.send(cardList);
});

app.get('/cardmap', function (req, res) {
  res.send(cardMap);
});

app.get('/card', function (req, res) {
    const name = normalizeName(req.query.card);
    const card = cardMap[name];
    if (!card)
        return res.status(500).send(`No card found for name ${name}`);
    console.log(`Card "${req.query.card}" -> "${name}": ${card}`);
    res.send(card);
});

app.get('/image', function (req, res) {
    const name = normalizeName(req.query.card);
    const card = cardMap[name];
    if (!card)
        return res.status(500).send(`No card found for name "${name}"`);
    const url = card.imageUrl;
    console.log(`Image "${req.query.card}" -> "${name}": ${url}`);
    res.contentType('jpeg');
    request.get(url).pipe(res);
});


app.listen(3000, () => {
    console.log('Example app listening on port 3000!');
});
